# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=26.1-pre-1
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Fabric API
fabric_api_version=0.143.12+26.1

# Mod Properties
mod_version = 2.0.0-alpha.1+26.1
maven_group = eu.pb4
archives_base_name = sgui

# Dependencies
# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api
